const crypto = require('crypto');

/**
 * Pairing: moving the master key from a device that has it to one that does not,
 * through a server that must not be able to read it or substitute itself.
 *
 * Both sides make an ephemeral X25519 pair, exchange public keys through the
 * server, and derive the same session key with HKDF-SHA256. The six digits the
 * user compares are DERIVED FROM BOTH PUBLIC KEYS, never generated by the
 * server: if the server swapped one key to sit in the middle, each side would
 * hash a different pair and the digits would disagree. Do not replace them with
 * a random code from the server — that removes the only thing this protocol
 * proves.
 *
 * Wire format for public keys: base64 of the raw 32-byte X25519 point.
 */

// SPKI DER prefix for an X25519 public key (RFC 8410). Raw point follows.
const X25519_SPKI_PREFIX = Buffer.from('302a300506032b656e032100', 'hex');
const RAW_PUB_BYTES = 32;
const HKDF_INFO = Buffer.from('termilab-pairing-v1', 'utf-8');
const DIGITS = 6;
const DIGITS_MOD = 1000000n;

function toRawPublicKey(keyObject) {
  const der = keyObject.export({ type: 'spki', format: 'der' });
  return der.subarray(der.length - RAW_PUB_BYTES);
}

function fromRawPublicKey(raw) {
  const buf = Buffer.isBuffer(raw) ? raw : Buffer.from(raw, 'base64');
  if (buf.length !== RAW_PUB_BYTES) {
    throw new Error(`Clave publica X25519 invalida: ${buf.length} bytes`);
  }
  return crypto.createPublicKey({
    key: Buffer.concat([X25519_SPKI_PREFIX, buf]),
    format: 'der',
    type: 'spki',
  });
}

/**
 * @returns {{privateKey: import('crypto').KeyObject, publicKey: import('crypto').KeyObject, pub: string}}
 *          `pub` is the base64 raw public key to send to the server.
 */
function generateEphemeralKeyPair() {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('x25519');
  return { privateKey, publicKey, pub: toRawPublicKey(publicKey).toString('base64') };
}

/**
 * Deterministic order for the two public keys, so neither side has to know
 * whether it is "A" or "B" to compute the same transcript.
 */
function sortedPubs(pubA, pubB) {
  const a = Buffer.isBuffer(pubA) ? pubA : Buffer.from(pubA, 'base64');
  const b = Buffer.isBuffer(pubB) ? pubB : Buffer.from(pubB, 'base64');
  if (a.length !== RAW_PUB_BYTES || b.length !== RAW_PUB_BYTES) {
    throw new Error('Clave publica X25519 invalida al ordenar el par');
  }
  return Buffer.compare(a, b) <= 0 ? [a, b] : [b, a];
}

/** SHA-256 over the ordered pair of public keys. Same on both devices. */
function transcriptHash(pubA, pubB) {
  const [first, second] = sortedPubs(pubA, pubB);
  return crypto.createHash('sha256').update(first).update(second).digest();
}

/**
 * The six digits the user compares out of band.
 * First 8 bytes of SHA-256(pubOrdenadaA || pubOrdenadaB), read as a big-endian
 * integer, modulo 10^6, zero-padded on the left.
 * @returns {string} e.g. "042917"
 */
function deriveDigits(pubA, pubB) {
  const h = transcriptHash(pubA, pubB);
  const n = BigInt(`0x${h.subarray(0, 8).toString('hex')}`) % DIGITS_MOD;
  return n.toString().padStart(DIGITS, '0');
}

/**
 * X25519 shared secret + HKDF-SHA256 -> 32-byte AES key.
 * The salt is the transcript hash of both public keys, so a swapped key also
 * breaks the key derivation, not just the digits.
 */
function deriveSessionKey(privateKey, peerPub, ownPub) {
  const peerKeyObject = fromRawPublicKey(peerPub);
  const shared = crypto.diffieHellman({ privateKey, publicKey: peerKeyObject });
  const salt = transcriptHash(ownPub, peerPub);
  const derived = crypto.hkdfSync('sha256', shared, salt, HKDF_INFO, 32);
  return Buffer.from(derived);
}

/**
 * Seals the master key for the peer. Reuses the record cipher (AES-256-GCM,
 * fresh 12-byte nonce, tag appended) so there is only one construction to audit.
 * @returns {{ciphertext: string, nonce: string}} base64
 */
function sealMasterKey(sessionKey, masterKey) {
  const cryptoService = require('./crypto-service');
  const buf = Buffer.isBuffer(masterKey) ? masterKey : Buffer.from(masterKey, 'base64');
  if (buf.length !== 32) throw new Error('La clave maestra a enviar no mide 32 bytes');
  // base64, not raw bytes: decryptWith returns utf-8 text and random bytes are
  // not valid utf-8, so a raw round trip would silently corrupt the key.
  return cryptoService.encryptWith(sessionKey, buf.toString('base64'));
}

/** @returns {Buffer} the 32-byte master key */
function openMasterKey(sessionKey, ciphertextB64, nonceB64) {
  const cryptoService = require('./crypto-service');
  const plaintext = cryptoService.decryptWith(sessionKey, ciphertextB64, nonceB64);
  const buf = Buffer.from(plaintext, 'base64');
  if (buf.length !== 32) {
    throw new Error(`La clave maestra recibida mide ${buf.length} bytes`);
  }
  return buf;
}

module.exports = {
  generateEphemeralKeyPair,
  deriveDigits,
  deriveSessionKey,
  sealMasterKey,
  openMasterKey,
  transcriptHash,
  toRawPublicKey,
  fromRawPublicKey,
};
